### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by MonkeSmart** [Randomblock1/webtoonimgdecoder#2]
Hello! Please, help. I can't get it working on the last step, on Windows 10:
`D:\Downloads\W>py -3 decoder.py D:\Downloads\W\images
  File "D:\Downloads\W\decoder.py", line 71
    <title>webtoonimgdecoder/decoder.py at master · Randomblock1/webtoonimgdecoder · GitHub</title>
                                                  ^
SyntaxError: invalid character '·' (U+00B7)`
Please, tell me, what am I doing wrong?
Thank you.

**Comment by Randomblock1** [comment]
It looks like you somehow downloaded a HTML page. Make sure you've `git clone`d properly.

**Comment by MonkeSmart** [comment]
Thank you very much. I indeed right-click-downloaded only decoder.py from the main page. Now I downloaded the full ZIP and it worked perfectly. Amazing tool. Thank you.
